import {
  Salina,
  Abhi,
  Sandy,
  Zohaib,
  Stephan,
  Amy,
  Annie,
  Carina,
  Cheryl,
  Melanie,
  Tristan,
  Uttej,
  Michael,
  Michelle,
  Peyton,
} from "../../images/team/index";

const executives = [
  {
    name: "Avan Chan",
    position: "President",
    linkedin: "https://www.linkedin.com/in/salina-guo-28409a1b1/",
    facebook: "https://www.facebook.com/salina.guo.7",
    instagram: "https://www.instagram.com/salinaguo/",
    email: "sguo.hba2025@ivey.ca",
    image: Tristan,
    calendly: "",
  },
  {
    name: "Tristan Mandy",
    position: "President",
    linkedin: "https://www.linkedin.com/in/stephan-balakumaran/",
    facebook: "https://www.facebook.com/profile.php?id=100010665544958",
    instagram: "https://www.instagram.com/stephanbalak/",
    email: "sbalakumaran.hba2025@ivey.ca",
    image: Tristan,
    calendly: "",
  },
  {
    name: "Abhi Ravipati",
    position: "VP Accelerator",
    facebook: "https://www.facebook.com/abhi.ravipati.50",
    linkedin: "https://www.linkedin.com/in/abhiravipati/",
    instagram: "https://www.instagram.com/_abhi_ravipati/",
    email: "aravipa@uwo.ca",
    image: Tristan,
    calendly: "about:blank",
  },
  {
    name: "Daniel Wang",
    position: "VP Accelerator",
    linkedin: "https://www.linkedin.com/in/daniel04wang/",
    instagram: "https://www.instagram.com/danieltnwang/",
    facebook:"https://www.facebook.com/profile.php?id=100044758291934",
    email: "dwang682@uwo.ca",
    image: Tristan,
    calendly: "",
  },
  {
    name: "Peyton Kou",
    position: "VP Community",
    linkedin: "https://www.linkedin.com/in/peyton-kou/",
    instagram: "https://www.instagram.com/paypeykay/",
    facebook: "https://www.facebook.com/peyton.kay.547",
    email: "pkou2@uwo.ca",
    image: Tristan,

  },
  {
    name: "Michael Chen",
    position: "VP Community",
    linkedin: "https://www.linkedin.com/in/michael-chen-015984216/",
    instagram: "https://www.instagram.com/michael.chenn04/",
    facebook: "hhttps://www.facebook.com/michaelchen0604",
    email: "mchen745@uwo.ca",
    image: Tristan,
    calendly: "https://calendly.com/sunny-su/w5community",
  },
  {
    name: "Mohammed Karimjee",
    position: "Co-VP Events",
    linkedin: "https://www.linkedin.com/in/mohammed-karimjee",
    instagram: "https://www.instagram.com/mohammedkarimjee/",
    facebook: "https://www.facebook.com/mohammed.karimjee.10",
    email: "Mkarimje@uwo.ca",
    image: Tristan,
    calendly: "https://calendly.com/mkarimje/30min",
  },
  {
    name: "Nathan Yee",
    position: "Co-VP Events",
    linkedin: "www.linkedin.com/in/nathancyee",
    instagram: "https://www.instagram.com/nathan.cyee/",
    facebook: "https://www.facebook.com/nate.yee.1",
    email: "nyee7@uwo.ca",
    image: Tristan,
    calendly: "https://calendly.com/nyee7",
  },
  {
    name: "Yusuf Nissar",
    position: "VP Finance",
    linkedin: "https://www.linkedin.com/in/yusufnissar/",
    instagram: "https://www.instagram.com/yusufnissar_/",
    facebook: "https://www.facebook.com/yusuf.nissar.96/",
    email: "yusufnissar8@gmail.com",
    image: Tristan,
    calendly: "https://calendly.com/yusufnissar/coffee-chats",
  },
  {
    name: "Orianna Lui",
    position: "Co-VP Marketing",
    linkedin: "https://www.linkedin.com/in/oriannaqlui/",
    instagram: "https://www.instagram.com/orianna.lui/",
    facebook: "https://www.facebook.com/oriannaqlui",
    email: "olui4@uwo.ca",
    image: Tristan,
    calendly: "https://calendly.com/oriannalui/coffee-chat",
  },
  {
    name: "Kelly Le",
    position: "Co-VP Marketing",
    linkedin: "https://www.linkedin.com/in/kelly-le-048120218",
    instagram: "https://www.instagram.com/kamanabilauta/",
    facebook: "https://www.facebook.com/KamanaBilauta",
    email: "kle65@uwo.ca",
    image: Tristan,
    calendly: "https://calendly.com/kle65/w5",
  },
  {
    name: "Grace Zhou",
    position: "Co-VP Projects",
    linkedin: "https://www.linkedin.com/in/grace-zhou-6364b717b/",
    instagram: "https://www.instagram.com/graz2003/",
    facebook: "https://www.facebook.com/messages/t/3995716953861476",
    email: "gzhou53@uwo.ca",
    image: Tristan,
    calendly: "https://calendly.com/zhougrace2003/w5",
  },
  {
    name: "Lena Qiu",
    position: "Co-VP Projects",
    linkedin: "https://www.linkedin.com/in/lena-tang-qiu-7b1b861b5",
    instagram: "https://www.instagram.com/lenaqtang/",
    facebook: "https://www.facebook.com/lena.qiutang",
    email: "ltang247@uwo.ca",
    image: Tristan,
    calendly: "https://calendly.com/lena-q-tang/coffee-chats",
  },
];

export { executives };
