import {
  Salina,
  Nathan,
  Sandy,
  Zohaib,
  Leanne,
  Mohammed,
  Stephan,
  Sunny,
  Grace,
  Kelly,
  Lena,
  Yusuf,
  Orianna,
} from "../../images/team/index";

const executives = [
  {
    name: "Sandy Wu",
    position: "Co-President",
    linkedin: "https://www.linkedin.com/in/sandywu102/",
    facebook: "https://www.facebook.com/sandyywu/",
    email: "sandywu2002@gmail.com",
    image: Sandy,
  },
  {
    name: "Zohaib Adnan",
    position: "Co-President",
    linkedin: "www.linkedin.com/in/zohaib12",
    facebook: "https://www.facebook.com/zohaib.adnan.14",
    email: "zohaib.adnan145@gmail.com",
    image: Zohaib,
  },
  {
    name: "Salina Guo",
    position: "Co-VP Accelerator",
    facebook: "https://www.facebook.com/salina.guo.7/",
    linkedin: "https://www.linkedin.com/in/salina-guo-28409a1b1/",
    email: "sguo272@uwo.ca",
    image: Salina,
  },
  {
    name: "Stephan Balakumaran",
    position: "Co-VP Accelerator",
    linkedin: "https://www.linkedin.com/in/stephan-balakumaran/",
    facebook:
      "https://www.facebook.com/people/Stephan-Balakumaran/100010665544958?_rdr",
    email: "sbalaku7@uwo.ca",
    image: Stephan,
  },
  {
    name: "Leanne Kwong",
    position: "Co-VP Community",
    linkedin: "https://www.linkedin.com/in/leannekwong/",
    facebook: "https://www.facebook.com/profile.php?id:100072431774219",
    email: "lkwong5@uwo.ca",
    image: Leanne,
  },
  {
    name: "Sunny Su",
    position: "Co-VP Community",
    linkedin: "https://www.linkedin.com/in/sunny-su/",
    facebook: "https://www.facebook.com/sunsun.su.969",
    email: "ssu63@uwo.ca",
    image: Sunny,
  },
  {
    name: "Mohammed Karimjee",
    position: "Co-VP Events",
    linkedin: "https://www.linkedin.com/in/mohammed-karimjee",
    facebook: "https://www.facebook.com/mohammed.karimjee.10",
    email: "Mkarimje@uwo.ca",
    image: Mohammed,
  },
  {
    name: "Nathan Yee",
    position: "Co-VP Events",
    linkedin: "www.linkedin.com/in/nathancyee",
    facebook: "https://www.facebook.com/nate.yee.1",
    email: "nyee7@uwo.ca",
    image: Nathan,
  },
  {
    name: "Yusuf Nissar",
    position: "VP Finance",
    linkedin: "https://www.linkedin.com/in/yusufnissar/",
    facebook: "https://www.facebook.com/yusuf.nissar.96/",
    email: "yusufnissar8@gmail.com",
    image: Yusuf,
  },
  {
    name: "Orianna Lui",
    position: "Co-VP Marketing",
    linkedin: "https://www.linkedin.com/in/oriannaqlui/",
    facebook: "https://www.facebook.com/oriannaqlui",
    email: "olui4@uwo.ca",
    image: Orianna,
  },
  {
    name: "Kelly Le",
    position: "Co-VP Marketing",
    linkedin: "https://www.linkedin.com/in/kelly-le-048120218",
    facebook: "https://www.facebook.com/KamanaBilauta",
    email: "kle65@uwo.ca",
    image: Kelly,
  },
  {
    name: "Grace Zhou",
    position: "Co-VP Projects",
    linkedin: "https://www.linkedin.com/in/grace-zhou-6364b717b/",
    facebook: "https://www.facebook.com/messages/t/3995716953861476",
    email: "gzhou53@uwo.ca",
    image: Grace,
  },
  {
    name: "Lena Qiu",
    position: "Co-VP Projects",
    linkedin: "https://www.linkedin.com/in/lena-tang-qiu-7b1b861b5",
    facebook: "https://www.facebook.com/lena.qiutang",
    email: "ltang247@uwo.ca",
    image: Lena,
  },
];

export { executives };
